/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_minify_in (XDR *xdrs, minify_in *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->src_val.src_val_val, (u_int *) &objp->src_val.src_val_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minify_out (XDR *xdrs, minify_out *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->dst_val.dst_val_val, (u_int *) &objp->dst_val.dst_val_len, ~0))
		 return FALSE;
	return TRUE;
}
