/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"
#include "steque.h"

#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h>
#include <getopt.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define USAGE                                                                 \
"usage:\n"                                                                    \
"  minifyjpeg_svc [options]\n"                                                  \
"options:\n"                                                                  \
"  -t [thread_count]   Thread count for work queue (Default: 3, Range: 1-31415)\n"      \
"  -h                  Show this help message\n"

/* OPTIONS DESCRIPTOR ====================================================== */
static struct option gLongOptions[] = {
  {"nthreads",           required_argument,      NULL,           't'},
  {"help",               no_argument,            NULL,           'h'},
  {NULL,                 0,                      NULL,             0}
};

typedef struct _request_t{
	minify_in input;
	struct svc_req *rqstp;
	SVCXPRT *transp;
} request_t;

pthread_t *thread_pool;
pthread_mutex_t queue_mutex;
pthread_cond_t	queue_is_empty;
steque_t requests;

void Usage() {
  fprintf(stdout, "%s", USAGE);
}

int
_minify_with_rpc_1 (minify_in  *argp, void *result, struct svc_req *rqstp)
{
	return (minify_with_rpc_1_svc(*argp, result, rqstp));
}

static void
minify_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	request_t *request;
	request = (request_t *) malloc(sizeof(request_t));
	
	union {
		minify_in minify_with_rpc_1_arg;
	} argument;
	/*union {
		minify_out minify_with_rpc_1_res;
	} result;*/
	//bool_t retval;
	xdrproc_t _xdr_argument;
	//bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MINIFY_WITH_RPC:
		_xdr_argument = (xdrproc_t) xdr_minify_in;
		//_xdr_result = (xdrproc_t) xdr_minify_out;
		//local = (bool_t (*) (char *, void *,  struct svc_req *))_minify_with_rpc_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	
	
	request->input = argument.minify_with_rpc_1_arg;
	request->rqstp = rqstp;
	request->transp = transp;
	
	pthread_mutex_lock(&queue_mutex);
	
	if(steque_isempty(&requests) == 1)
	{
		steque_push(&requests, (steque_item) request);
		pthread_mutex_unlock(&queue_mutex);
		pthread_cond_broadcast(&queue_is_empty);
	}
	else
	{
		steque_push(&requests, (steque_item) request);
		pthread_mutex_unlock(&queue_mutex);
	}	
		
		
	
	/*retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!minify_rpc_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");*/

	return;
}

void *requestHandler()
{
	request_t *request;
	bool_t (*local)(char *, void *, struct svc_req *);
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	_xdr_argument = (xdrproc_t) xdr_minify_in;
	_xdr_result = (xdrproc_t) xdr_minify_out;
	
	union {
		minify_out minify_with_rpc_1_res;
	} result;
	
	while(1){
	
		pthread_mutex_lock(&queue_mutex);
		
		while(steque_isempty(&requests) == 1)
		{
			pthread_cond_wait(&queue_is_empty, &queue_mutex);
		}
		
		request = (request_t *) steque_pop(&requests);
			
		pthread_mutex_unlock(&queue_mutex);
		
		
		
		
		local = (bool_t (*) (char *, void *,  struct svc_req *))_minify_with_rpc_1;
		
		
		
		
		retval = (bool_t) (*local)((char *)&request->input, (void *)&result, request->rqstp);
		if (retval > 0 && !svc_sendreply(request->transp, (xdrproc_t) _xdr_result, (char *)&result)) {
			svcerr_systemerr (request->transp);
		}
		if (!svc_freeargs (request->transp, (xdrproc_t) _xdr_argument, (caddr_t) &request->input)) {
			fprintf (stderr, "%s", "unable to free arguments");
			exit (1);
		}
		if (!minify_rpc_1_freeresult (request->transp, _xdr_result, (caddr_t) &result))
			fprintf (stderr, "%s", "unable to free results");
		
		free(request);
	}
}

void initializeThreads(int nthreads)
{
	thread_pool = (pthread_t *) malloc(sizeof(pthread_t) * nthreads);
	
	pthread_mutex_init(&queue_mutex, NULL);
	pthread_cond_init(&queue_is_empty, NULL);
	
	for(int i = 0; i < nthreads; i++)
	{
		pthread_create(&thread_pool[i], NULL, requestHandler, NULL);
	}
	
	return;
}

int
main (int argc, char **argv)
{
	int nthreads = 3;
	register SVCXPRT *transp;
	char option_char;
	
	while ((option_char = getopt_long(argc, argv, "ic:ht:", gLongOptions, NULL)) != -1) {
		switch (option_char) {
			default:
				Usage();
				exit(1);
			case 'h': // help
				Usage();
				exit(0);
				break;    
			case 't': // thread-count
				nthreads = atoi(optarg);
				break;   
		}
	}
	
	steque_init(&requests);
	initializeThreads(nthreads);

	pmap_unset (MINIFY_RPC, MINIFY_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIFY_RPC, MINIFY_VERS, minify_rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MINIFY_RPC, MINIFY_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIFY_RPC, MINIFY_VERS, minify_rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MINIFY_RPC, MINIFY_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
